// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $blog_slug_ from "./routes/blog/[...slug].tsx";
import * as $gfm_css from "./routes/gfm.css.ts";
import * as $index from "./routes/index.tsx";
import * as $reels_hhtw from "./routes/reels/hhtw.tsx";
import * as $showcase from "./routes/showcase.tsx";
import * as $talks_sg_cityjsconf_2024 from "./routes/talks/sg-cityjsconf-2024.tsx";
import * as $talks_sgoss from "./routes/talks/sgoss.tsx";
import * as $talks_twml from "./routes/talks/twml.tsx";
import * as $ElevenLabsAudioNative from "./islands/ElevenLabsAudioNative.tsx";
import * as $InstagramReelsEmbed from "./islands/InstagramReelsEmbed.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_middleware.ts": $_middleware,
    "./routes/blog/[...slug].tsx": $blog_slug_,
    "./routes/gfm.css.ts": $gfm_css,
    "./routes/index.tsx": $index,
    "./routes/reels/hhtw.tsx": $reels_hhtw,
    "./routes/showcase.tsx": $showcase,
    "./routes/talks/sg-cityjsconf-2024.tsx": $talks_sg_cityjsconf_2024,
    "./routes/talks/sgoss.tsx": $talks_sgoss,
    "./routes/talks/twml.tsx": $talks_twml,
  },
  islands: {
    "./islands/ElevenLabsAudioNative.tsx": $ElevenLabsAudioNative,
    "./islands/InstagramReelsEmbed.tsx": $InstagramReelsEmbed,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
