// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/blog/[...slug].tsx";
import * as $4 from "./routes/gfm.css.ts";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/showcase.tsx";
import * as $7 from "./routes/talks/sg-cityjsconf-2024.tsx";
import * as $8 from "./routes/talks/sgoss.tsx";
import * as $9 from "./routes/talks/twml.tsx";
import * as $$0 from "./islands/ElevenLabsAudioNative.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/blog/[...slug].tsx": $3,
    "./routes/gfm.css.ts": $4,
    "./routes/index.tsx": $5,
    "./routes/showcase.tsx": $6,
    "./routes/talks/sg-cityjsconf-2024.tsx": $7,
    "./routes/talks/sgoss.tsx": $8,
    "./routes/talks/twml.tsx": $9,
  },
  islands: {
    "./islands/ElevenLabsAudioNative.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
